services:
  - type: web
    name: him-public-school
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false